---
title: "Homework 01"
output:
    pdf_document: default
---

```{r setup, include=FALSE, chache = F}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(error = TRUE)
```

\let\OldRule\rule
\renewcommand{\rule}[2]{\OldRule{\linewidth}{#2}}

----------

# Task 1

## 1.8

## 1.8.a
```{r}
x <- 5
(5 * x^2 - 2 * x + 1)^10
sqrt((5 * x)^5 + (3 * x)^3)
log(2^x + exp(3 * x)^3)
sin(exp(3 * cos(x^2)))
k <- 1:1000
sum(2^(-k))
```

## 1.8.b
```{r}
family <- ordered(c("Eltern", "Enkel", "Kinder", "Grosseltern", "Kinder", "Enkel"),
                  levels = c("Enkel", "Kinder", "Eltern", "Grosseltern")) # ordinal
companies <- factor(c("Google", "Apple", "Amazon", "SAP", "Disney", "Netflix")) # nominal
numbers <- c(75, 63.5, 53, 89, 113, 75) # quantitative
sizes <- ordered("riesig", "klein", "groß", "winzig", "normal", "gigantisch",
                 levels = c("winzig", "klein", "normal", "groß", "riesig", "gigantisch")) # ordinal
colors <- factor(c("rot", "blau", "violett", "orange", "gelb", "grün")) # nominal
```

## 1.9
```{r}
# 1.9.a
age <- c("35-44", "25-34", "18-24", "45-54", "35-44", "35-44", "35-44", "25-34")
job <- c("Krankenpfleger:in", "Krankenpfleger:in", "Hebamme/Geburtshelfer", "Aerztin/Arzt",
         "Aerztin/Arzt", "Krankenpfleger:in", "Krankenpfleger:in", "Aerztin/Arzt")
height <- c(175, 182, 169, 196, 168, 170, 156, 165)
weight <- c(80, 75, 62, 85, 79, 90, 65, 60)
df <- data.frame("Altersgruppe"=age, "Beruf"=job, "Groesse in cm"=height, "Gewicht in kg"=weight, check.names = FALSE)

# 1.9.b
df[df$"Altersgruppe" == "35-44",]

# 1.9.c
df$bmi <- df$"Gewicht in kg" / (df$"Groesse in cm" / 100)^2
df <- df[, c(1:2, 5, 3:4)]

# 1.9.d
mean(df$bmi)
mean(df[df$"Altersgruppe" == "35-44",]$bmi)
```

# 1.10
```{r}
# 1.10.a
survey.adelaide <- read.csv("data/Example0.5.csv")

# 1.10.b
str(survey.adelaide) # shows the table head and the data type of each column
head(survey.adelaide) # shows the head and the first 6 rows (tail() would show the last 6)
summary(survey.adelaide) # shows the summary of the data (min, max, mean, median, etc.)

# 1.10.c
mean(survey.adelaide$Wr.Hnd[survey.adelaide$Smoke != "Never"], na.rm = TRUE)
```
