---
title: "Homework 04"
output: pdf_document
---

```{r setup, include=FALSE, chache = F}
knitr::opts_knit$set(root.dir = normalizePath(".."))
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(error = TRUE)
```

\let\OldRule\rule
\renewcommand{\rule}[2]{\OldRule{\linewidth}{#2}}

----------

# Task 4
## Task 4.8
### 4.8.a
```{r}
par(mfrow = c(1, 3))
n <- c(10, 15, 20)
p <- c(0.5, 0.75, 0.3)

for (i in 1:3) {
  dist <- rbinom(1000, n[i], p[i])
  plot(table(dist) / 1000, main = paste("n =", n[i], "p =", p[i]), xlab = expression(k), ylab = expression(p(k)))
  points(dbinom(1:n[i], n[i], p[i]), pch = 16, col = "red")
}
```

### 4.8.b
```{r}
p <- c(0.3, 0.6)
par(mfrow = c(1, 2))

for (i in 1:2) {
  dist <- rgeom(1000, p[i])
  plot(table(dist) / 1000, main = paste("p =", p[i]), xlab = expression(k), ylab = expression(p(k)))
  points(dgeom(1:20, p[i]), pch = 16, col = "red")
}
```

### 4.8.c
```{r}
N <- c(12, 20)
K <- c(7, 15)
n <- c(4, 10)
par(mfrow = c(1, 2))

for (i in 1:2) {
  dist <- rhyper(1000, N[i], K[i], n[i])
  plot(table(dist) / 1000,
       main = paste("N =", N[i], "K =", K[i], "n =", n[i]),
       xlab = expression(k), ylab = expression(p(k)))
  points(dhyper(0:n[i], N[i], K[i], n[i]), pch = 16, col = "red")
}
```

### 4.8.d
```{r}
lambda <- c(1, 2, 4)
par(mfrow = c(1, 3))

for (i in 1:3) {
  dist <- rpois(1000, lambda[i])
  plot(table(dist) / 1000, main = paste("lambda =", lambda[i]), xlab = expression(k), ylab = expression(p(k)))
  points(dpois(0:20, lambda[i]), pch = 16, col = "red")
}
```
